// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009211940_newPhone")]
    partial class newPhone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppRolePermission", b =>
                {
                    b.Property<string>("AppRolesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.HasKey("AppRolesId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("AppRolePermission", "dbo");

                    b.HasData(
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 1
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 2
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 3
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 4
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 5
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 6
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 7
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 8
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 9
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 10
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 11
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 12
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 13
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 14
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 15
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 16
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 17
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 18
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 19
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 20
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 21
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 22
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 23
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 24
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 25
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 26
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 27
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 28
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 29
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 30
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 31
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 32
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 34
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 35
                        },
                        new
                        {
                            AppRolesId = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            PermissionsId = 36
                        });
                });

            modelBuilder.Entity("FinalProject.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "73e78560-eaf0-4ea4-81aa-0dc71bb65ae0",
                            Name = "Adminstrator"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RoleAppId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleAppId");

                    b.ToTable("User", "dbo");
                });

            modelBuilder.Entity("FinalProject.Models.Attendance", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountHours")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN DATEDIFF(HOUR, ArrivalTime, DepartureTime) < 8 AND DATEDIFF(HOUR, ArrivalTime, DepartureTime) > 3 THEN 8 - DATEDIFF(HOUR, ArrivalTime, DepartureTime) ELSE 0 END");

                    b.Property<int>("ExtraHours")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN DATEDIFF(HOUR, ArrivalTime, DepartureTime) > 8  THEN DATEDIFF(HOUR, ArrivalTime, DepartureTime) - 8 ELSE 0 END");

                    b.Property<bool>("IsAbsent")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CONVERT(bit, CASE WHEN DATEDIFF(HOUR, ArrivalTime, DepartureTime) <= 3 THEN 1 ELSE 0 END)");

                    b.HasKey("Date", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances", "dbo");
                });

            modelBuilder.Entity("FinalProject.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "R & D"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableVacations")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeptID");

                    b.HasIndex("UserId");

                    b.ToTable("Employees", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1998, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "East Idell",
                            ContractDate = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Belize",
                            DeptID = 3,
                            Email = "employee1@hrsm.com",
                            FirstName = "Jaleel",
                            Gender = 1,
                            LastName = "Nat",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 263566.0,
                            Street = "Rath Forest"
                        },
                        new
                        {
                            Id = 2,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "West Mateo",
                            ContractDate = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Kazakhstan",
                            DeptID = 2,
                            Email = "employee2@hrsm.com",
                            FirstName = "Malachi",
                            Gender = 1,
                            LastName = "Adan",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 11531.0,
                            Street = "Herman Lodge"
                        },
                        new
                        {
                            Id = 3,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "West Enriquemouth",
                            ContractDate = new DateTime(2021, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Wallis and Futuna",
                            DeptID = 3,
                            Email = "employee3@hrsm.com",
                            FirstName = "Nannie",
                            Gender = 1,
                            LastName = "Jesus",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 332157.0,
                            Street = "Cecilia Underpass"
                        },
                        new
                        {
                            Id = 4,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1997, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Deshawnside",
                            ContractDate = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "British Virgin Islands",
                            DeptID = 2,
                            Email = "employee4@hrsm.com",
                            FirstName = "Leda",
                            Gender = 1,
                            LastName = "Alvis",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 164726.0,
                            Street = "Cormier Pike"
                        },
                        new
                        {
                            Id = 5,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "West Cheyanne",
                            ContractDate = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Angola",
                            DeptID = 3,
                            Email = "employee5@hrsm.com",
                            FirstName = "Alisa",
                            Gender = 0,
                            LastName = "Christian",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 241821.0,
                            Street = "Cummerata Grove"
                        },
                        new
                        {
                            Id = 6,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1998, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "North Lisandro",
                            ContractDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Iraq",
                            DeptID = 3,
                            Email = "employee6@hrsm.com",
                            FirstName = "Jude",
                            Gender = 0,
                            LastName = "Bertrand",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 74171.0,
                            Street = "Jerome Haven"
                        },
                        new
                        {
                            Id = 7,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "East Myah",
                            ContractDate = new DateTime(2020, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Paraguay",
                            DeptID = 3,
                            Email = "employee7@hrsm.com",
                            FirstName = "Elijah",
                            Gender = 0,
                            LastName = "Delphia",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 116358.0,
                            Street = "Sofia Court"
                        },
                        new
                        {
                            Id = 8,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1999, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "North Mayaville",
                            ContractDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Macao",
                            DeptID = 2,
                            Email = "employee8@hrsm.com",
                            FirstName = "Sheridan",
                            Gender = 1,
                            LastName = "Keshawn",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 118165.0,
                            Street = "Bauch Lodge"
                        },
                        new
                        {
                            Id = 9,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1995, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "VonRuedenchester",
                            ContractDate = new DateTime(2021, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Saint Lucia",
                            DeptID = 2,
                            Email = "employee9@hrsm.com",
                            FirstName = "Jerrold",
                            Gender = 1,
                            LastName = "Earnestine",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 288194.0,
                            Street = "Mitchell Summit"
                        },
                        new
                        {
                            Id = 10,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1995, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "North Fletcher",
                            ContractDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Austria",
                            DeptID = 3,
                            Email = "employee10@hrsm.com",
                            FirstName = "Al",
                            Gender = 0,
                            LastName = "Jayden",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 93943.0,
                            Street = "Kessler Points"
                        },
                        new
                        {
                            Id = 11,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "South Lindsay",
                            ContractDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Grenada",
                            DeptID = 2,
                            Email = "employee11@hrsm.com",
                            FirstName = "Mekhi",
                            Gender = 1,
                            LastName = "Jed",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 186323.0,
                            Street = "Larson Rapid"
                        },
                        new
                        {
                            Id = 12,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1991, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Vonside",
                            ContractDate = new DateTime(2020, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Yemen",
                            DeptID = 2,
                            Email = "employee12@hrsm.com",
                            FirstName = "Adella",
                            Gender = 0,
                            LastName = "Hannah",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 473888.0,
                            Street = "Freeda Knoll"
                        },
                        new
                        {
                            Id = 13,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1990, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Hansenborough",
                            ContractDate = new DateTime(2020, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Liberia",
                            DeptID = 2,
                            Email = "employee13@hrsm.com",
                            FirstName = "Sydnee",
                            Gender = 0,
                            LastName = "Kaylin",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 381210.0,
                            Street = "Boehm Mission"
                        },
                        new
                        {
                            Id = 14,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Port Devanborough",
                            ContractDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Paraguay",
                            DeptID = 2,
                            Email = "employee14@hrsm.com",
                            FirstName = "Deborah",
                            Gender = 0,
                            LastName = "Shayna",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 220865.0,
                            Street = "Una Gateway"
                        },
                        new
                        {
                            Id = 15,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1996, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Fritschbury",
                            ContractDate = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Slovenia",
                            DeptID = 2,
                            Email = "employee15@hrsm.com",
                            FirstName = "Dasia",
                            Gender = 1,
                            LastName = "Dimitri",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 189021.0,
                            Street = "Anderson Mill"
                        },
                        new
                        {
                            Id = 16,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Camyllemouth",
                            ContractDate = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Gabon",
                            DeptID = 1,
                            Email = "employee16@hrsm.com",
                            FirstName = "Marlene",
                            Gender = 1,
                            LastName = "Nikolas",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 24350.0,
                            Street = "Ebert Meadow"
                        },
                        new
                        {
                            Id = 17,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1997, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Keeblershire",
                            ContractDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "India",
                            DeptID = 3,
                            Email = "employee17@hrsm.com",
                            FirstName = "Kellie",
                            Gender = 0,
                            LastName = "Sid",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 299443.0,
                            Street = "Brendan Viaduct"
                        },
                        new
                        {
                            Id = 18,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1990, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Lake Stacy",
                            ContractDate = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Congo",
                            DeptID = 2,
                            Email = "employee18@hrsm.com",
                            FirstName = "Pattie",
                            Gender = 1,
                            LastName = "Emmet",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 61097.0,
                            Street = "Carter Via"
                        },
                        new
                        {
                            Id = 19,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Santinaburgh",
                            ContractDate = new DateTime(2020, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Azerbaijan",
                            DeptID = 2,
                            Email = "employee19@hrsm.com",
                            FirstName = "Dortha",
                            Gender = 1,
                            LastName = "Raphael",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 340693.0,
                            Street = "Stacy Overpass"
                        },
                        new
                        {
                            Id = 20,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1999, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New Louie",
                            ContractDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Ukraine",
                            DeptID = 3,
                            Email = "employee20@hrsm.com",
                            FirstName = "Lilliana",
                            Gender = 0,
                            LastName = "Johanna",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 386471.0,
                            Street = "Estevan Junctions"
                        },
                        new
                        {
                            Id = 21,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1993, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "South Gilbert",
                            ContractDate = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Bahrain",
                            DeptID = 1,
                            Email = "employee21@hrsm.com",
                            FirstName = "Darion",
                            Gender = 1,
                            LastName = "Aida",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 289717.0,
                            Street = "Funk Unions"
                        },
                        new
                        {
                            Id = 22,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "South Johnson",
                            ContractDate = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Afghanistan",
                            DeptID = 3,
                            Email = "employee22@hrsm.com",
                            FirstName = "Cortez",
                            Gender = 1,
                            LastName = "Summer",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 22082.0,
                            Street = "Colleen Cove"
                        },
                        new
                        {
                            Id = 23,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "West Reese",
                            ContractDate = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Jordan",
                            DeptID = 1,
                            Email = "employee23@hrsm.com",
                            FirstName = "Naomi",
                            Gender = 1,
                            LastName = "Keaton",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 46654.0,
                            Street = "O'Conner Lane"
                        },
                        new
                        {
                            Id = 24,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2000, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "North Aileenton",
                            ContractDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Aruba",
                            DeptID = 3,
                            Email = "employee24@hrsm.com",
                            FirstName = "Daija",
                            Gender = 0,
                            LastName = "Eli",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 314314.0,
                            Street = "Maggio Tunnel"
                        },
                        new
                        {
                            Id = 25,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Boylemouth",
                            ContractDate = new DateTime(2020, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Poland",
                            DeptID = 3,
                            Email = "employee25@hrsm.com",
                            FirstName = "Tara",
                            Gender = 1,
                            LastName = "Valerie",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 196428.0,
                            Street = "Anahi Well"
                        },
                        new
                        {
                            Id = 26,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1997, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Bahringerport",
                            ContractDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Finland",
                            DeptID = 3,
                            Email = "employee26@hrsm.com",
                            FirstName = "Nicole",
                            Gender = 0,
                            LastName = "Salma",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 45360.0,
                            Street = "Ole Haven"
                        },
                        new
                        {
                            Id = 27,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Lake Elian",
                            ContractDate = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Morocco",
                            DeptID = 3,
                            Email = "employee27@hrsm.com",
                            FirstName = "Adolph",
                            Gender = 1,
                            LastName = "Novella",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 303215.0,
                            Street = "Romaguera Court"
                        },
                        new
                        {
                            Id = 28,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1998, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "East Brennon",
                            ContractDate = new DateTime(2021, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Paraguay",
                            DeptID = 3,
                            Email = "employee28@hrsm.com",
                            FirstName = "Osborne",
                            Gender = 0,
                            LastName = "Katelin",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 11386.0,
                            Street = "Hagenes Station"
                        },
                        new
                        {
                            Id = 29,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1990, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Krystinafurt",
                            ContractDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United States Virgin Islands",
                            DeptID = 2,
                            Email = "employee29@hrsm.com",
                            FirstName = "Malinda",
                            Gender = 0,
                            LastName = "Greyson",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 412898.0,
                            Street = "Zemlak Ridge"
                        },
                        new
                        {
                            Id = 30,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1991, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "East Angelicatown",
                            ContractDate = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Cocos (Keeling) Islands",
                            DeptID = 1,
                            Email = "employee30@hrsm.com",
                            FirstName = "America",
                            Gender = 1,
                            LastName = "Rhoda",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 223430.0,
                            Street = "Catharine Rue"
                        },
                        new
                        {
                            Id = 31,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1991, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New Jakaylachester",
                            ContractDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Switzerland",
                            DeptID = 2,
                            Email = "employee31@hrsm.com",
                            FirstName = "Odessa",
                            Gender = 0,
                            LastName = "Florencio",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 211439.0,
                            Street = "Kuhlman Lodge"
                        },
                        new
                        {
                            Id = 32,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "North Edd",
                            ContractDate = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Peru",
                            DeptID = 1,
                            Email = "employee32@hrsm.com",
                            FirstName = "Kendall",
                            Gender = 0,
                            LastName = "Scarlett",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 484335.0,
                            Street = "Milford Trail"
                        },
                        new
                        {
                            Id = 33,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Port Royal",
                            ContractDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Western Sahara",
                            DeptID = 3,
                            Email = "employee33@hrsm.com",
                            FirstName = "Aditya",
                            Gender = 1,
                            LastName = "Fidel",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 215248.0,
                            Street = "Beier Coves"
                        },
                        new
                        {
                            Id = 34,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2002, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Tomburgh",
                            ContractDate = new DateTime(2022, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Western Sahara",
                            DeptID = 1,
                            Email = "employee34@hrsm.com",
                            FirstName = "Christa",
                            Gender = 1,
                            LastName = "Elody",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 162419.0,
                            Street = "Nitzsche Junctions"
                        },
                        new
                        {
                            Id = 35,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "West Camylle",
                            ContractDate = new DateTime(2020, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United States of America",
                            DeptID = 1,
                            Email = "employee35@hrsm.com",
                            FirstName = "Tressa",
                            Gender = 0,
                            LastName = "Eryn",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 127230.0,
                            Street = "Greta Cape"
                        },
                        new
                        {
                            Id = 36,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1992, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Glennachester",
                            ContractDate = new DateTime(2022, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Bahrain",
                            DeptID = 2,
                            Email = "employee36@hrsm.com",
                            FirstName = "Jany",
                            Gender = 0,
                            LastName = "Chaya",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 456236.0,
                            Street = "Ortiz Estate"
                        },
                        new
                        {
                            Id = 37,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Americoport",
                            ContractDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Montserrat",
                            DeptID = 3,
                            Email = "employee37@hrsm.com",
                            FirstName = "Brielle",
                            Gender = 1,
                            LastName = "Samir",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 493629.0,
                            Street = "Kris Squares"
                        },
                        new
                        {
                            Id = 38,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2000, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Samantabury",
                            ContractDate = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Belgium",
                            DeptID = 2,
                            Email = "employee38@hrsm.com",
                            FirstName = "Jedidiah",
                            Gender = 0,
                            LastName = "Jaron",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 299139.0,
                            Street = "Considine Throughway"
                        },
                        new
                        {
                            Id = 39,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1996, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gennarofort",
                            ContractDate = new DateTime(2021, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Chile",
                            DeptID = 2,
                            Email = "employee39@hrsm.com",
                            FirstName = "Laurie",
                            Gender = 1,
                            LastName = "Joey",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 116067.0,
                            Street = "Kailey Flat"
                        },
                        new
                        {
                            Id = 40,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1993, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "North Cheyenne",
                            ContractDate = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Gambia",
                            DeptID = 2,
                            Email = "employee40@hrsm.com",
                            FirstName = "Enrique",
                            Gender = 1,
                            LastName = "Lavern",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 300427.0,
                            Street = "Jamir Point"
                        },
                        new
                        {
                            Id = 41,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2001, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Port Esther",
                            ContractDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Kuwait",
                            DeptID = 3,
                            Email = "employee41@hrsm.com",
                            FirstName = "Sofia",
                            Gender = 1,
                            LastName = "Jane",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 387792.0,
                            Street = "Kshlerin Crossing"
                        },
                        new
                        {
                            Id = 42,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1993, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Lake Mikelfurt",
                            ContractDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Bahamas",
                            DeptID = 2,
                            Email = "employee42@hrsm.com",
                            FirstName = "Kenton",
                            Gender = 1,
                            LastName = "Alena",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 205549.0,
                            Street = "Wehner Ville"
                        },
                        new
                        {
                            Id = 43,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(2001, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Phoebefurt",
                            ContractDate = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Indonesia",
                            DeptID = 2,
                            Email = "employee43@hrsm.com",
                            FirstName = "Lucie",
                            Gender = 0,
                            LastName = "Maymie",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 151851.0,
                            Street = "Jerry Drive"
                        },
                        new
                        {
                            Id = 44,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1995, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Fannyview",
                            ContractDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Heard Island and McDonald Islands",
                            DeptID = 1,
                            Email = "employee44@hrsm.com",
                            FirstName = "Dustin",
                            Gender = 1,
                            LastName = "Germaine",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 267462.0,
                            Street = "Wiza Ridge"
                        },
                        new
                        {
                            Id = 45,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1990, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Lake Josiane",
                            ContractDate = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Kenya",
                            DeptID = 1,
                            Email = "employee45@hrsm.com",
                            FirstName = "Tracy",
                            Gender = 1,
                            LastName = "Howell",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 52963.0,
                            Street = "Felton Grove"
                        },
                        new
                        {
                            Id = 46,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1995, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Port Ocie",
                            ContractDate = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "New Caledonia",
                            DeptID = 1,
                            Email = "employee46@hrsm.com",
                            FirstName = "Jensen",
                            Gender = 1,
                            LastName = "Ephraim",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 392306.0,
                            Street = "Nettie Valleys"
                        },
                        new
                        {
                            Id = 47,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1996, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Itzelfort",
                            ContractDate = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Belize",
                            DeptID = 1,
                            Email = "employee47@hrsm.com",
                            FirstName = "Alfred",
                            Gender = 1,
                            LastName = "Kristopher",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 134366.0,
                            Street = "Lempi Wells"
                        },
                        new
                        {
                            Id = 48,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1992, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New Vilmamouth",
                            ContractDate = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Lesotho",
                            DeptID = 1,
                            Email = "employee48@hrsm.com",
                            FirstName = "Destinee",
                            Gender = 0,
                            LastName = "Greg",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 495446.0,
                            Street = "Monahan Landing"
                        },
                        new
                        {
                            Id = 49,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1996, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "East Zelda",
                            ContractDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Greece",
                            DeptID = 3,
                            Email = "employee49@hrsm.com",
                            FirstName = "Elsie",
                            Gender = 1,
                            LastName = "Bert",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 39852.0,
                            Street = "Bridgette Lodge"
                        },
                        new
                        {
                            Id = 50,
                            AvailableVacations = 21,
                            BirthDate = new DateTime(1998, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Trompchester",
                            ContractDate = new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Namibia",
                            DeptID = 1,
                            Email = "employee50@hrsm.com",
                            FirstName = "Keely",
                            Gender = 0,
                            LastName = "Alexander",
                            NationalId = "12345678901234",
                            Password = "12345678",
                            PhoneNumber = "01096366618",
                            Salary = 350866.0,
                            Street = "Crooks Island"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.GeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DiscountHourPrice")
                        .HasColumnType("int");

                    b.Property<int>("ExtraHourPrice")
                        .HasColumnType("int");

                    b.Property<int>("PriceForDayOvernumberofvacationInyear")
                        .HasColumnType("int");

                    b.Property<int>("numberofvacationInyear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GeneralSetting", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountHourPrice = 150,
                            ExtraHourPrice = 75,
                            PriceForDayOvernumberofvacationInyear = 300,
                            numberofvacationInyear = 21
                        });
                });

            modelBuilder.Entity("FinalProject.Models.OfficialVacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OfficalVacations", "dbo");
                });

            modelBuilder.Entity("FinalProject.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Employee",
                            Operation = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee",
                            Operation = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Employee",
                            Operation = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee",
                            Operation = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Attendance",
                            Operation = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Attendance",
                            Operation = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Attendance",
                            Operation = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Attendance",
                            Operation = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "AppRole",
                            Operation = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "AppRole",
                            Operation = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "AppRole",
                            Operation = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "AppRole",
                            Operation = 0
                        },
                        new
                        {
                            Id = 13,
                            Name = "AppUser",
                            Operation = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "AppUser",
                            Operation = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "AppUser",
                            Operation = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "AppUser",
                            Operation = 0
                        },
                        new
                        {
                            Id = 17,
                            Name = "Permission",
                            Operation = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Permission",
                            Operation = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Permission",
                            Operation = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Permission",
                            Operation = 0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Department",
                            Operation = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Department",
                            Operation = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Department",
                            Operation = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Department",
                            Operation = 0
                        },
                        new
                        {
                            Id = 25,
                            Name = "OfficialVacation",
                            Operation = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "OfficialVacation",
                            Operation = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "OfficialVacation",
                            Operation = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "OfficialVacation",
                            Operation = 0
                        },
                        new
                        {
                            Id = 29,
                            Name = "Vacation",
                            Operation = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Vacation",
                            Operation = 2
                        },
                        new
                        {
                            Id = 31,
                            Name = "Vacation",
                            Operation = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "Vacation",
                            Operation = 0
                        },
                        new
                        {
                            Id = 34,
                            Name = "GeneralSetting",
                            Operation = 1
                        },
                        new
                        {
                            Id = 35,
                            Name = "GeneralSetting",
                            Operation = 2
                        },
                        new
                        {
                            Id = 36,
                            Name = "Salary",
                            Operation = 1
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Vacation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VacationType")
                        .HasColumnType("int");

                    b.HasKey("StartDate", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vacations", "dbo");
                });

            modelBuilder.Entity("FinalProject.Models.WeeklyHoliday", b =>
                {
                    b.Property<string>("Holiday")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Genral_Id")
                        .HasColumnType("int");

                    b.HasKey("Holiday", "Genral_Id");

                    b.HasIndex("Genral_Id");

                    b.ToTable("WeeklyHolidays", "dbo");
                });

            modelBuilder.Entity("FinalProject.ViewModels.EmployeeAttendanceVM", b =>
                {
                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.ToTable("EmployeeAttendanceReport", "dbo");
                });

            modelBuilder.Entity("FinalProject.ViewModels.SettingViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("Extra")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SettingViewModel", "dbo");
                });

            modelBuilder.Entity("FinalProject.ViewModels.WeekDaysViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SettingViewModelid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SettingViewModelid");

                    b.ToTable("WeekDaysViewModel", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("AppRolePermission", b =>
                {
                    b.HasOne("FinalProject.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("AppRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject.Models.AppUser", b =>
                {
                    b.HasOne("FinalProject.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleAppId");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinalProject.Models.Attendance", b =>
                {
                    b.HasOne("FinalProject.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FinalProject.Models.Employee", b =>
                {
                    b.HasOne("FinalProject.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject.Models.OfficialVacation", b =>
                {
                    b.HasOne("FinalProject.Models.AppUser", "User")
                        .WithMany("OfficalVacations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject.Models.Vacation", b =>
                {
                    b.HasOne("FinalProject.Models.Employee", "Employee")
                        .WithMany("Vacations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FinalProject.Models.WeeklyHoliday", b =>
                {
                    b.HasOne("FinalProject.Models.GeneralSetting", "GenrealSetting")
                        .WithMany("DayOffPerWeek")
                        .HasForeignKey("Genral_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenrealSetting");
                });

            modelBuilder.Entity("FinalProject.ViewModels.WeekDaysViewModel", b =>
                {
                    b.HasOne("FinalProject.ViewModels.SettingViewModel", null)
                        .WithMany("DayChecked")
                        .HasForeignKey("SettingViewModelid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("FinalProject.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FinalProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FinalProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("FinalProject.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FinalProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject.Models.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FinalProject.Models.AppUser", b =>
                {
                    b.Navigation("OfficalVacations");
                });

            modelBuilder.Entity("FinalProject.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("FinalProject.Models.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Vacations");
                });

            modelBuilder.Entity("FinalProject.Models.GeneralSetting", b =>
                {
                    b.Navigation("DayOffPerWeek");
                });

            modelBuilder.Entity("FinalProject.ViewModels.SettingViewModel", b =>
                {
                    b.Navigation("DayChecked");
                });
#pragma warning restore 612, 618
        }
    }
}
